/**
 * production-downtime-extract.test.ts — L-051, END TO END through `extractMc`.
 *
 * The parser has its own unit tests; this file proves the WHOLE extractor produces the
 * right downtime row from a sheet laid out exactly like MC's. Every sheet below is a
 * faithful reconstruction of a real day from
 * "260911 Daily Production Report 2026 3Q.xlsx" (59 day tabs, 2026-07-01…09-11) — same
 * anchors, same columns, same cell text — so the two figures Renzo can check by hand are
 * asserted against the real code path:
 *
 *     2026-09-03  →  118 minutes  (8:00-8:07 + 9:50-11:41), DURATION blank
 *     2026-07-04  →   77 minutes  (8:00 AM-8:07 AM + 12:20 PM-1:30 PM), DURATION "7 MINUTES"
 *
 * A build-it-in-memory workbook rather than a committed .xlsx, so the exact cell text
 * under test is readable in the diff.
 */
import { describe, it, expect } from "vitest";
import ExcelJS from "exceljs";

import { loadProductionWorkbook } from "../../src/reports/production/sheet.js";
import { extractMc, type DowntimeRow } from "../../src/reports/production/extractMc.js";

interface DaySpec {
  /** Sheet title, `MM-DD-YY`. */
  name: string;
  /** Runs block: [grade, sacks, kg, column-H label]. */
  runs: Array<[string, number | null, number | null, string | null]>;
  /** Downtime block: category / time ranges / DURATION / reason. */
  category: string;
  ranges: string;
  duration: string;
  reason: string;
  /** CHARCOAL FED block: 1ST SHIFT and OVERTIME sacks. */
  fedFirst: number;
  fedOvertime: number;
}

/**
 * Lay out one day the way MC's 3Q template does: runs at rows 8-12, TOTAL at 14, the
 * downtime category at 25 / `DURATION` header at 26 / detail at 28, and the CHARCOAL FED
 * block anchored at J22 with `1ST SHIFT` at 25 and `OVERTIME` at 26.
 */
function addDay(wb: ExcelJS.Workbook, d: DaySpec): void {
  const ws = wb.addWorksheet(d.name);
  ws.getCell("C7").value = "SHIFT";
  ws.getCell("D7").value = "MESH SIZES";
  ws.getCell("G7").value = "TOTAL";
  d.runs.forEach(([grade, sacks, kg, shift], i) => {
    const r = 8 + i;
    ws.getCell(`D${r}`).value = grade;
    if (sacks !== null) ws.getCell(`E${r}`).value = sacks;
    if (kg !== null) ws.getCell(`G${r}`).value = kg;
    if (shift !== null) ws.getCell(`H${r}`).value = shift;
  });
  ws.getCell("C14").value = "TOTAL";
  ws.getCell("G14").value = d.runs.reduce((s, [, , kg]) => s + (kg ?? 0), 0);

  ws.getCell("J22").value = "CHARCOAL FED";
  ws.getCell("J24").value = "1ST SHIFT";
  ws.getCell("K24").value = "SACKS";
  ws.getCell("J25").value = "1ST SHIFT";
  ws.getCell("K25").value = d.fedFirst;
  ws.getCell("J26").value = "OVERTIME";
  ws.getCell("K26").value = d.fedOvertime;
  ws.getCell("J27").value = "Total";
  ws.getCell("K27").value = d.fedFirst + d.fedOvertime;

  ws.getCell("C25").value = d.category;
  ws.getCell("F26").value = "DURATION";
  ws.getCell("C28").value = d.ranges;
  ws.getCell("E28").value = d.duration;
  ws.getCell("F28").value = d.reason;
}

async function extractDays(days: DaySpec[]): Promise<DowntimeRow[]> {
  const wb = new ExcelJS.Workbook();
  for (const d of days) addDay(wb, d);
  const loaded = await loadProductionWorkbook(Buffer.from(await wb.xlsx.writeBuffer()));
  return extractMc(loaded, 2026, "2026-01-01").downtime;
}

/** 2026-09-03 — DURATION blank since August; the list says 118 minutes. */
const SEP_3: DaySpec = {
  name: "09-03-26",
  runs: [
    ["CEBU 3X50", 732, 19032, null],
    ["6X50", 15, 8550, null],
    ["KOREA POWDER (BAGGED)", 1, null, null],
  ],
  category: "REPAIR",
  ranges: "8:00-8:07\n\n9:50-11:41",
  duration: "",
  reason:
    "CLEANED SCREEN RS 2A, RS 2B, AND 6X50 PROD TANK\n\nSC #54 STOCK UP AND CHANGED MOTOR",
  fedFirst: 1000,
  fedOvertime: 0,
};

/** 2026-07-04 — DURATION covers only the FIRST range; the list says 77 minutes. */
const JUL_4: DaySpec = {
  name: "07-04-26",
  runs: [
    ["CEBU 3X50", 561, 14586, "DAY SHIFT"],
    ["CEBU 3X50", 200, 5200, "OVERTIME"],
    ["4X8", 10, 5750, "DAY SHIFT"],
    ["4X8", 5, 2875, "OVERTIME"],
  ],
  category: "REPAIR",
  ranges: "8:00 AM-8:07 AM\n\n12:20 PM-1:30 PM",
  duration: "7 MINUTES",
  reason: "CLEANED SCREENS RS 2A, RS 2B\n\nREPAIR SCREEN 1 PC CONNECTED TO FRAME 3",
  fedFirst: 775,
  fedOvertime: 375,
};

/** 2026-08-05 — the brown-out: four bare marks, no dashes, no DURATION. */
const AUG_5: DaySpec = {
  name: "08-05-26",
  runs: [["CEBU 3X50", 968, 25168, null]],
  category: "REPAIR",
  ranges: "8:00\n\n8:22\n\n3:00\n\n3:09",
  duration: "",
  reason: "BROWN OUT DLPC\n\nSTART OPERATION GENERATED BY GENSET\n\nPOWER IS BACK\n\nSTART OPERATION",
  fedFirst: 900,
  fedOvertime: 0,
};

/** 2026-07-17 — the whole downtime detail row blank, only the category printed. */
const JUL_17: DaySpec = {
  name: "07-17-26",
  runs: [["CEBU 3X50", null, null, null]],
  category: "REPAIR",
  ranges: "",
  duration: "",
  reason: "",
  fedFirst: 0,
  fedOvertime: 0,
};

/** 2026-08-11 — one range, and the reason says the plant never stopped (L-051b). */
const AUG_11: DaySpec = {
  name: "08-11-26",
  runs: [["CEBU 3X50", 1015, 26390, null]],
  category: "REPAIR",
  ranges: "8:00-11:37",
  duration: "",
  reason:
    "CHANGED MOTOR ROLLER MILL #1 AND CHANGED HANGER BEARING 1 PC FOR BE #6 CONNECTED TO " +
    "RS 5. NO STOP OPERATION",
  fedFirst: 900,
  fedOvertime: 0,
};

describe("extractMc downtime — L-051, the real sheet shapes", () => {
  it("2026-09-03 reads 118 minutes from the ranges (DURATION blank)", async () => {
    const [dt] = await extractDays([SEP_3]);
    expect(dt.transaction_date).toBe("2026-09-03");
    expect(dt.dt_hrs * 60 + dt.dt_mins).toBe(118);
    expect(dt.dt_hrs).toBe(1);
    expect(dt.dt_mins).toBe(58);
    expect(dt.dt_ranges).toBe("8:00-8:07; 9:50-11:41");
    expect(dt._minutes_source).toBe("ranges");
    expect(dt._duration_disagrees).toBeUndefined();
    // No overtime kilos and 0 overtime sacks → the ordinary 8-hour day.
    expect(dt.shift_hrs).toBe(9);
    expect(dt.shift_hrs_source).toBe("default_9h");
  });

  it("2026-07-04 reads 77 minutes and flags the DURATION cell's 7", async () => {
    const [dt] = await extractDays([JUL_4]);
    expect(dt.dt_hrs * 60 + dt.dt_mins).toBe(77);
    expect(dt.dt_hrs).toBe(1);
    expect(dt.dt_mins).toBe(17);
    expect(dt._duration_mins).toBe(7);
    expect(dt._ranges_mins).toBe(77);
    expect(dt._duration_disagrees).toBe(true);
    expect(dt.warnings.join(" ")).toContain("used the ranges");
    // OVERTIME runs with kilos AND 375 overtime sacks → the 12-hour day.
    expect(dt.shift_hrs).toBe(12);
    expect(dt.shift_hrs_source).toBe("overtime_signal");
  });

  it("2026-08-05 pairs the brown-out marks into 31 minutes", async () => {
    const [dt] = await extractDays([AUG_5]);
    expect(dt.dt_hrs).toBe(0);
    expect(dt.dt_mins).toBe(31);
    expect(dt.dt_ranges).toBe("8:00; 8:22; 3:00; 3:09");
    expect(dt.shift_hrs).toBe(9);
  });

  it("2026-07-17 still emits a reason-only row with no minutes and no ranges", async () => {
    const [dt] = await extractDays([JUL_17]);
    expect(dt.dt_hrs).toBe(0);
    expect(dt.dt_mins).toBe(0);
    expect(dt.dt_reason).toBe("REPAIR");
    expect(dt.dt_ranges).toBeNull();
    expect(dt._minutes_source).toBe("none");
    // A blank DURATION is not a disagreement, so this day raises no note.
    expect(dt._duration_disagrees).toBeUndefined();
  });

  it("2026-08-11 records ZERO downtime and keeps the range as an incident (L-051b)", async () => {
    const [dt] = await extractDays([AUG_11]);
    expect(dt.dt_hrs).toBe(0);
    expect(dt.dt_mins).toBe(0);
    // The time is NOT lost — it moves to the incident column and stays in dt_ranges.
    expect(dt.dt_ranges).toBe("8:00-11:37");
    expect(dt.dt_incident_ranges).toBe("8:00-11:37");
    expect(dt.dt_reason).toContain("NO STOP OPERATION");
    // A measured zero, not a failed read: the ranges WERE the source.
    expect(dt._minutes_source).toBe("ranges");
    expect(dt.shift_hrs).toBe(9);
  });

  it("a whole workbook of days keeps each day's own figures", async () => {
    const rows = await extractDays([JUL_4, AUG_5, SEP_3, JUL_17, AUG_11]);
    expect(rows.map((r) => r.dt_hrs * 60 + r.dt_mins)).toEqual([77, 31, 118, 0, 0]);
    expect(rows.map((r) => r.shift_hrs)).toEqual([12, 9, 9, 9, 9]);
    expect(rows.map((r) => r.dt_incident_ranges)).toEqual([
      null, null, null, null, "8:00-11:37",
    ]);
  });
});
