/**
 * norm.test.ts — value-parity tests for the norm.ts ports.
 *
 * The expected values come from test/fixtures/norm-parity.json, which was
 * GENERATED BY RUNNING THE ACTUAL PYTHON norm/coerce functions
 * (npm run gen:fixtures). If any of these fail, the TS port diverges from the
 * Python oracle and would cause silent classification drift — the #1 risk in the
 * migration. Do NOT "fix" a test by editing the fixture; regenerate it.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  normNum,
  normIntTrunc,
  normIntRound,
  normStr,
  normBlockLoc,
  coerceDate,
  roundHalfToEven,
  coerceFloat,
  excelSerialToISO,
} from "../src/lib/norm.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(resolve(__dirname, "fixtures/norm-parity.json"), "utf8")
) as {
  cases: {
    num: Array<{ v: unknown; places: number; expected: number | null }>;
    int: Array<{ v: unknown; expected_trunc: number | null; expected_round: number | null }>;
    str: Array<{ v: unknown; expected: string | null }>;
    block: Array<{ v: unknown; expected: string | null }>;
    date: Array<{ v: unknown; expected: string | null }>;
  };
};

describe("normNum — banker's rounding parity with Python round()", () => {
  for (const c of fixture.cases.num) {
    it(`normNum(${JSON.stringify(c.v)}, ${c.places}) === ${JSON.stringify(c.expected)}`, () => {
      expect(normNum(c.v, c.places)).toBe(c.expected);
    });
  }
});

describe("normIntTrunc — Python int(float(v)) (deliveries)", () => {
  for (const c of fixture.cases.int) {
    it(`normIntTrunc(${JSON.stringify(c.v)}) === ${JSON.stringify(c.expected_trunc)}`, () => {
      expect(normIntTrunc(c.v)).toBe(c.expected_trunc);
    });
  }
});

describe("normIntRound — Python int(round(float(v))) (gsheet)", () => {
  for (const c of fixture.cases.int) {
    it(`normIntRound(${JSON.stringify(c.v)}) === ${JSON.stringify(c.expected_round)}`, () => {
      expect(normIntRound(c.v)).toBe(c.expected_round);
    });
  }
});

describe("normStr — Python norm_str", () => {
  for (const c of fixture.cases.str) {
    it(`normStr(${JSON.stringify(c.v)}) === ${JSON.stringify(c.expected)}`, () => {
      expect(normStr(c.v)).toBe(c.expected);
    });
  }
});

describe("normBlockLoc — Python norm_block_loc", () => {
  for (const c of fixture.cases.block) {
    it(`normBlockLoc(${JSON.stringify(c.v)}) === ${JSON.stringify(c.expected)}`, () => {
      expect(normBlockLoc(c.v)).toBe(c.expected);
    });
  }
});

describe("coerceDate — Python coerce_date (string paths)", () => {
  for (const c of fixture.cases.date) {
    it(`coerceDate(${JSON.stringify(c.v)}) === ${JSON.stringify(c.expected)}`, () => {
      expect(coerceDate(c.v)).toBe(c.expected);
    });
  }
});

describe("coerceDate — Date object path (exceljs surfaces Date for date cells)", () => {
  it("UTC Date -> its Y-M-D", () => {
    expect(coerceDate(new Date(Date.UTC(2026, 6, 2)))).toBe("2026-07-02");
  });
  it("UTC Date with time component -> date only", () => {
    expect(coerceDate(new Date(Date.UTC(2026, 0, 1, 13, 30)))).toBe("2026-01-01");
  });
  it("invalid Date -> null", () => {
    expect(coerceDate(new Date("nonsense"))).toBe(null);
  });
});

describe("roundHalfToEven — direct spot checks", () => {
  // These mirror documented CPython behavior exactly.
  it("round(0.5) == 0", () => expect(roundHalfToEven(0.5)).toBe(0));
  it("round(1.5) == 2", () => expect(roundHalfToEven(1.5)).toBe(2));
  it("round(2.5) == 2", () => expect(roundHalfToEven(2.5)).toBe(2));
  it("round(2.675, 2) == 2.67 (binary noise)", () =>
    expect(roundHalfToEven(2.675, 2)).toBe(2.67));
  it("round(0.135, 2) == 0.14 (binary noise up)", () =>
    expect(roundHalfToEven(0.135, 2)).toBe(0.14));
  it("round(0.145, 2) == 0.14 (binary noise down)", () =>
    expect(roundHalfToEven(0.145, 2)).toBe(0.14));
  it("round(-2.5) == -2", () => expect(roundHalfToEven(-2.5)).toBe(-2));
  it("no negative zero", () => expect(Object.is(roundHalfToEven(-0.0, 3), 0)).toBe(true));
});

describe("coerceFloat — Python coerce_float (extract_rc_deliveries)", () => {
  it("null/empty -> null", () => {
    expect(coerceFloat(null)).toBe(null);
    expect(coerceFloat("")).toBe(null);
  });
  it("boolean rejected -> null", () => {
    expect(coerceFloat(true)).toBe(null);
    expect(coerceFloat(false)).toBe(null);
  });
  it("number passthrough", () => expect(coerceFloat(21789.0000001)).toBe(21789.0000001));
  it("strips commas / peso / dollar", () => {
    expect(coerceFloat("₱1,234.56")).toBe(1234.56);
    expect(coerceFloat("$2,000")).toBe(2000);
  });
  it("unparseable -> null", () => expect(coerceFloat("abc")).toBe(null));
});

describe("excelSerialToISO — 1900 date system", () => {
  // 45845 = 2025-07-08 in Excel's 1900 system. 44927 = 2023-01-01.
  it("44927 -> 2023-01-01", () => expect(excelSerialToISO(44927)).toBe("2023-01-01"));
  it("non-finite -> null", () => expect(excelSerialToISO(NaN)).toBe(null));
});
