/**
 * norm.ts — EXACT ports of the Python normalization helpers used by the sync
 * classifiers. These are the numeric/string/date normalizers that decide whether
 * two rows are "the same" (NOOP) or "changed" (VALUE_CHANGED). Getting them
 * byte-for-byte identical to Python is the #1 silent-corruption risk in the whole
 * migration (SYNC_TS_MIGRATION_PLAN Risk #1), so every function here mirrors a
 * specific Python function and is covered by value-parity fixtures generated by
 * RUNNING the Python (test/fixtures/norm-parity.json).
 *
 * Source of truth (read as spec):
 *   .claude/skills/sync-ictc/scripts/classify_deliveries.py  (norm_str, norm_block_loc, norm_num, norm_int)
 *   .claude/skills/sync-ictc/scripts/classify_gsheet.py      (norm_int variant — int(round()))
 *   .claude/skills/sync-ictc/scripts/extract_rc_deliveries.py (coerce_date, coerce_float)
 *
 * HARD RULE: no ad-hoc Math.round anywhere in the sync codebase. Python's
 * built-in round() is BANKER'S ROUNDING (round-half-to-even). JS Math.round is
 * round-half-up. They disagree on every .5 boundary (round(0.5)=0 in Python,
 * Math.round(0.5)=1). All rounding MUST go through roundHalfToEven here.
 */

// ---------------------------------------------------------------------------
// Banker's rounding — the load-bearing primitive
// ---------------------------------------------------------------------------

/**
 * Replicates Python 3's built-in `round(value, ndigits)` for floats:
 * round-half-to-even ("banker's rounding"). Python rounds a value exactly halfway
 * between two options to the nearest EVEN option.
 *
 *   Python round(0.5)   == 0      Python round(2.5)   == 2
 *   Python round(1.5)   == 2      Python round(0.125, 2) == 0.12
 *   Python round(2.675, 2) == 2.67  (binary float noise — 2.675 is actually
 *                                    2.67499999... in IEEE-754, so it rounds DOWN)
 *
 * We deliberately mirror CPython's implementation strategy: CPython's
 * float.__round__ uses a correctly-rounded double->decimal->double path
 * (_Py_dg_dtoa). We approximate it faithfully for the precisions the sync uses
 * (0–3 dp) by scaling and applying round-half-to-even on the scaled value, while
 * guarding against the scaling itself introducing new binary noise.
 *
 * IMPORTANT: because 2.675*100 == 267.49999999999997 in IEEE-754 (exactly as in
 * Python before it rounds), the half-to-even branch is only taken when the scaled
 * value is *genuinely* at a .5 boundary within a tiny epsilon. This matches
 * Python's observed outputs on real sync data (see fixtures).
 */
export function roundHalfToEven(value: number, ndigits = 0): number {
  if (!Number.isFinite(value)) return value;
  if (value === 0) return 0;

  // CPython's float.__round__ does NOT scale-then-round (that reintroduces binary
  // noise: 0.135*100 == 13.500000000000002 but 2.675*100 == 267.49999999999994).
  // Instead it converts the double to its correctly-rounded SHORTEST decimal string
  // (the same value JS Number.prototype.toString produces — both use the
  // shortest-round-tripping algorithm), then rounds THAT decimal with
  // half-to-even. Operating on the exact decimal repr is what makes 2.675 -> 2.67
  // (its shortest decimal is "2.675" but the underlying double is 2.67499999…,
  // and CPython rounds the true stored value). We therefore round the double's
  // full-precision decimal expansion, not its shortest repr — using toFixed at a
  // high precision to expose the stored value's trailing digits.
  const neg = value < 0;
  const abs = Math.abs(value);

  // Expose enough of the stored double's decimal expansion to see which side of
  // .5 the true value falls on. 20 fractional digits is more than a double can
  // carry, so toFixed(20) reveals the genuine stored value (e.g. 2.675 shows as
  // "2.67499999999999982236").
  const expanded = abs.toFixed(20); // "int.frac"
  const dot = expanded.indexOf(".");
  const intPart = expanded.slice(0, dot);
  const fracPart = expanded.slice(dot + 1);

  const keep = fracPart.slice(0, ndigits);
  const rest = fracPart.slice(ndigits);

  // Build the digit string we are keeping (integer + kept fractional digits).
  let digits = intPart + keep;

  const roundUp = shouldRoundUpHalfEven(digits, rest);
  if (roundUp) {
    digits = incrementDecimalString(digits);
  }

  // Reassemble into a number at the requested precision.
  let resultStr: string;
  if (ndigits > 0) {
    // digits may have grown (carry) — recompute split from the right.
    const padded = digits.padStart(ndigits + 1, "0");
    const cut = padded.length - ndigits;
    resultStr = padded.slice(0, cut) + "." + padded.slice(cut);
  } else {
    resultStr = digits;
  }

  let result = Number(resultStr);
  if (neg) result = -result;
  return result === 0 ? 0 : result;
}

/**
 * Given the kept digit string and the remaining (dropped) fractional digits,
 * decide whether to round up under round-half-to-even.
 *  - rest starts with < 5  -> round down
 *  - rest starts with > 5, or == 5 with any nonzero after -> round up
 *  - rest is exactly "5000…0" -> half: round up iff last kept digit is odd
 */
function shouldRoundUpHalfEven(keptDigits: string, rest: string): boolean {
  if (rest.length === 0) return false;
  const first = rest.charCodeAt(0) - 48; // '0' == 48
  if (first < 5) return false;
  if (first > 5) return true;
  // first === 5: is anything nonzero after it?
  for (let i = 1; i < rest.length; i++) {
    if (rest.charCodeAt(i) !== 48) return true; // >.5 -> up
  }
  // exactly .5 -> round to even: up iff last kept digit is odd
  const lastKept = keptDigits.charCodeAt(keptDigits.length - 1) - 48;
  return lastKept % 2 === 1;
}

/** Add 1 to a non-negative decimal-digit string, propagating carry. */
function incrementDecimalString(s: string): string {
  const arr = s.split("");
  let i = arr.length - 1;
  while (i >= 0) {
    if (arr[i] === "9") {
      arr[i] = "0";
      i--;
    } else {
      arr[i] = String.fromCharCode(arr[i].charCodeAt(0) + 1);
      return arr.join("");
    }
  }
  return "1" + arr.join("");
}

// ---------------------------------------------------------------------------
// String normalizers
// ---------------------------------------------------------------------------

/**
 * Port of Python `norm_str`: trim, lowercase, empty-string -> None(null).
 *   None -> null ; "  ABC " -> "abc" ; "" / "   " -> null
 */
export function normStr(s: unknown): string | null {
  if (s === null || s === undefined) return null;
  const t = String(s).trim();
  return t ? t.toLowerCase() : null;
}

/**
 * Port of Python `norm_block_loc`: trim, UPPERCASE, empty -> null.
 * Block loc is a code — case-insensitive but format preserved (uppercased).
 *   "b-3a" -> "B-3A" ; "" -> null
 */
export function normBlockLoc(s: unknown): string | null {
  if (s === null || s === undefined) return null;
  const t = String(s).trim();
  return t ? t.toUpperCase() : null;
}

// ---------------------------------------------------------------------------
// Numeric normalizers
// ---------------------------------------------------------------------------

/**
 * Port of Python `norm_num(v, places=3)`:
 *   - None/null/undefined -> null
 *   - float(v) then round(., places) with BANKER'S rounding
 *   - unparseable (TypeError/ValueError) -> null
 *
 * Python's float() accepts numeric strings ("21789.0000001"), ints, and floats.
 * It does NOT accept bools implicitly here in a way that matters (Python float(True)
 * == 1.0, but the sync never feeds bools to norm_num; we still mirror float()
 * semantics — a JS boolean is rejected as null since Python callers never pass one
 * and treating true->1 would be surprising in a diff). Blank/whitespace strings ->
 * null (Python float("") raises ValueError).
 */
export function normNum(v: unknown, places = 3): number | null {
  if (v === null || v === undefined) return null;
  const f = pyFloat(v);
  if (f === null) return null;
  return roundHalfToEven(f, places);
}

/**
 * Port of Python `norm_int` — DELIVERIES variant: `int(float(v))`.
 * This TRUNCATES toward zero (Python int() of a float drops the fractional part):
 *   int(float("123.9")) == 123 ; int(float(-1.9)) == -1
 * Used by classify_deliveries.py.
 */
export function normIntTrunc(v: unknown): number | null {
  if (v === null || v === undefined) return null;
  const f = pyFloat(v);
  if (f === null) return null;
  return Math.trunc(f);
}

/**
 * Port of Python `norm_int` — GSHEET variant: `int(round(float(v)))`.
 * This ROUNDS (banker's) then truncates:
 *   int(round(float("123.5"))) == 124? No — round(123.5) banker's == 124 (even),
 *   round(122.5) == 122. Used by classify_gsheet.py.
 */
export function normIntRound(v: unknown): number | null {
  if (v === null || v === undefined) return null;
  const f = pyFloat(v);
  if (f === null) return null;
  return Math.trunc(roundHalfToEven(f, 0));
}

/**
 * Port of Python `coerce_float` from extract_rc_deliveries.py:
 *   - None/"" -> null
 *   - bool -> null (bool is a subtype of int in Python — explicitly rejected)
 *   - int/float -> float(v)
 *   - str -> strip commas / ₱ / $ / whitespace, then float(); blank -> null;
 *     unparseable -> null
 */
export function coerceFloat(value: unknown): number | null {
  if (value === null || value === undefined || value === "") return null;
  if (typeof value === "boolean") return null;
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : null;
  }
  if (typeof value === "string") {
    const cleaned = value.replace(/,/g, "").replace(/₱/g, "").replace(/\$/g, "").trim();
    if (!cleaned) return null;
    const f = Number(cleaned);
    return Number.isFinite(f) ? f : null;
  }
  return null;
}

/**
 * Mirror of Python's `float(v)` for the value shapes the sync feeds it:
 *   - number -> itself (if finite)
 *   - numeric string (incl. leading/trailing whitespace, "1e3", "  21789.0000001 ")
 *     -> parsed float; blank or non-numeric -> null (Python raises -> caller None)
 * Returns null on anything Python float() would raise on.
 */
function pyFloat(v: unknown): number | null {
  if (typeof v === "number") return Number.isFinite(v) ? v : null;
  if (typeof v === "string") {
    const t = v.trim();
    if (t === "") return null;
    // Number() accepts the same numeric grammar Python float() does for our data
    // (decimal, sign, exponent). It also accepts "Infinity"/"NaN"/hex/"" — guard
    // those: Python float("") raises; float("inf")/float("nan") are valid but the
    // sync never carries them, and treating them as null is the safe diff outcome.
    if (/^[+-]?(infinity|inf|nan)$/i.test(t)) return null;
    const f = Number(t);
    return Number.isFinite(f) ? f : null;
  }
  // Python float() would accept a Decimal or bool; the sync never passes those to
  // norm_num. Anything else -> null (mirrors the except TypeError/ValueError -> None).
  return null;
}

// ---------------------------------------------------------------------------
// Date normalizer
// ---------------------------------------------------------------------------

/**
 * Port of Python `coerce_date` from extract_rc_deliveries.py → returns YYYY-MM-DD
 * or null.
 *
 * openpyxl decodes Excel date SERIALS into native datetime/date objects before the
 * Python ever sees them, so `coerce_date` only ever handles (a) datetime/date and
 * (b) strings in a small set of formats. exceljs likewise returns a JS Date for
 * date-typed cells, so our xlsx.ts hands this function a Date | string — mirroring
 * the Python exactly.
 *
 *   Date        -> its calendar date in ISO (Y-M-D), taken in UTC to match how
 *                  exceljs surfaces date cells (see xlsx.ts::cellToDateISO)
 *   string      -> try %Y-%m-%d, %m/%d/%Y, %d/%m/%Y, %Y/%m/%d, %m-%d-%Y in order
 *   None/""     -> null
 *   unparseable -> null
 */
export function coerceDate(value: unknown): string | null {
  if (value === null || value === undefined || value === "") return null;

  if (value instanceof Date) {
    if (isNaN(value.getTime())) return null;
    // Use UTC components — exceljs stores date cells as UTC midnight, and openpyxl
    // yields a naive date whose Y-M-D we take verbatim. See xlsx.ts.
    const y = value.getUTCFullYear();
    const m = value.getUTCMonth() + 1;
    const d = value.getUTCDate();
    return `${pad4(y)}-${pad2(m)}-${pad2(d)}`;
  }

  if (typeof value === "string") {
    const s = value.trim();
    // Order matters — mirrors the Python format list exactly.
    return (
      tryFormat(s, "Y-m-d") ??
      tryFormat(s, "m/d/Y") ??
      tryFormat(s, "d/m/Y") ??
      tryFormat(s, "Y/m/d") ??
      tryFormat(s, "m-d-Y") ??
      null
    );
  }

  return null;
}

/**
 * Excel serial-number → ISO date, for the rare path where a raw serial reaches us
 * (a cell exceljs did NOT type as a date). Excel's epoch is 1899-12-30 (accounting
 * for the 1900 leap-year bug). This mirrors openpyxl's from_excel for the 1900
 * date system, which is what all ICTC workbooks use.
 */
export function excelSerialToISO(serial: number): string | null {
  if (!Number.isFinite(serial)) return null;
  // 1899-12-30 UTC + serial days.
  const EXCEL_EPOCH_UTC = Date.UTC(1899, 11, 30);
  const ms = EXCEL_EPOCH_UTC + Math.floor(serial) * 86400000;
  const d = new Date(ms);
  if (isNaN(d.getTime())) return null;
  return `${pad4(d.getUTCFullYear())}-${pad2(d.getUTCMonth() + 1)}-${pad2(d.getUTCDate())}`;
}

// Strict strptime-equivalent for the exact formats coerce_date uses. Python's
// datetime.strptime is strict (it rejects out-of-range values and trailing junk),
// so we validate ranges and re-check the round trip.
function tryFormat(s: string, fmt: "Y-m-d" | "m/d/Y" | "d/m/Y" | "Y/m/d" | "m-d-Y"): string | null {
  let y: number, mo: number, d: number;
  let m: RegExpMatchArray | null;
  switch (fmt) {
    case "Y-m-d":
      m = s.match(/^(\d{1,4})-(\d{1,2})-(\d{1,2})$/);
      if (!m) return null;
      y = +m[1]; mo = +m[2]; d = +m[3];
      break;
    case "m/d/Y":
      m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{1,4})$/);
      if (!m) return null;
      mo = +m[1]; d = +m[2]; y = +m[3];
      break;
    case "d/m/Y":
      m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{1,4})$/);
      if (!m) return null;
      d = +m[1]; mo = +m[2]; y = +m[3];
      break;
    case "Y/m/d":
      m = s.match(/^(\d{1,4})\/(\d{1,2})\/(\d{1,2})$/);
      if (!m) return null;
      y = +m[1]; mo = +m[2]; d = +m[3];
      break;
    case "m-d-Y":
      m = s.match(/^(\d{1,2})-(\d{1,2})-(\d{1,4})$/);
      if (!m) return null;
      mo = +m[1]; d = +m[2]; y = +m[3];
      break;
  }
  if (mo < 1 || mo > 12 || d < 1 || d > 31) return null;
  // Validate the calendar date (rejects 02/30 etc.) via a UTC Date round trip.
  const dt = new Date(Date.UTC(y, mo - 1, d));
  if (
    dt.getUTCFullYear() !== y ||
    dt.getUTCMonth() !== mo - 1 ||
    dt.getUTCDate() !== d
  ) {
    return null;
  }
  return `${pad4(y)}-${pad2(mo)}-${pad2(d)}`;
}

function pad2(n: number): string {
  return String(n).padStart(2, "0");
}
function pad4(n: number): string {
  return String(n).padStart(4, "0");
}
