/**
 * downtimeRanges.ts — read MC's downtime block the way a PERSON reads it.
 *
 * L-051, 2026-09-14. THE ONE SENTENCE: **a duration a human types is a SUMMARY of a list
 * they also typed — read the list.**
 *
 * MC's downtime block carries the stoppages TWICE. Column C is the LIST: one time range
 * per line, in the order the plant stopped and restarted. Column E is a hand-written
 * DURATION, a courtesy total. The extractor read column E and only column E, so:
 *
 *   - From 2026-08-01 MC simply STOPPED filling column E. Every August and September day
 *     therefore extracted `0 minutes` beside a fully-populated list of ranges — the
 *     database published `0.0 downtime hours` for two whole months (23 of 23 August rows
 *     and 10 of 10 September rows were reason-only) while the workbook stated, for
 *     example on 2026-09-03, `8:00-8:07` and `9:50-11:41` = 118 minutes.
 *   - Even while column E WAS filled it usually summarised only the FIRST range
 *     (2026-07-04: ranges 7 min + 70 min, DURATION `7 MINUTES`), so July was understated
 *     too.
 *   - And the old digit-strip parse (`replace(/[^0-9.]/g, "")`) mangled the two-part form:
 *     `"1 HOUR & 40 MINUTES"` became the number **140**, not 100.
 *
 * So the ranges are the primary reading and the DURATION is demoted to a CROSS-CHECK.
 * When the two disagree the ranges win and the run says so — the duration cell has been
 * measured to be a partial summary, the list has not.
 *
 * ── Reading a time ──────────────────────────────────────────────────────────
 * Times appear as `H:MM` with an OPTIONAL meridiem (`AM`, `PM`, or `NN` for noon, which
 * MC uses for the 12 o'clock hour). Since 2026-08 the meridiem is usually absent, so a
 * bare `3:00` has to be resolved. THE PLANT DAY STARTS AT 08:00 — every single downtime
 * block in both surviving workbooks opens with an `8:00` range — so an hour of 1–7 is
 * unambiguously the AFTERNOON and 8–12 is the morning (12 being noon). That is the only
 * assumption in this module, and it is the operator's own convention, not a guess:
 * `12:58-1:05` is 12:58 → 13:05, `3:00-3:09` is 15:00 → 15:09.
 *
 * ── What is NOT counted, and why ────────────────────────────────────────────
 *   - An OPEN range (a start with no end, e.g. `3:22 PM`, or the truncated `3:55 PM-`)
 *     contributes ZERO and raises a warning naming it. MC writes these as event marks
 *     ("ADJUST INVERTER TO 30:30"), not as stoppages, and inventing an end time would be
 *     fiction. NULL is not zero, but an unmeasurable span is not a number either — the
 *     honest answer is to count nothing and say which line was skipped.
 *   - A span whose end precedes its start after the plant-day rule contributes zero and
 *     warns. Refusing is the only safe answer; a negative stoppage is not a stoppage.
 *
 * ── The one exception to "a bare time is an open range" ─────────────────────
 * A cell that contains NO dashed span at all but DOES contain several bare times is the
 * brown-out shape: 2026-08-05 reads `8:00 / 8:22 / 3:00 / 3:09` against the reasons
 * `BROWN OUT DLPC / START OPERATION GENERATED BY GENSET / POWER IS BACK / START
 * OPERATION` — four marks that are two stoppages written without dashes. Consecutive
 * bare times are paired ONLY in that case (no dashed span anywhere in the cell), so a
 * lone event mark sitting BESIDE a real range — 2026-07-13's `8:00 AM-10:03 AM` then
 * `3:22 PM` — can never be silently glued to the next line. A leftover odd time falls
 * back to the open-range rule.
 *
 * Pure and dependency-free: no DB, no Excel, no clock. Every rule here is exercised
 * against the real cell text in test/reports/production-downtime-ranges.test.ts.
 */

/** One resolved stoppage, in minutes from midnight. */
export interface DowntimeSpan {
  /** Verbatim source text of this span, for the audit trail. */
  raw: string;
  /** Start, minutes from midnight (0-1439). */
  startMin: number;
  /** End, minutes from midnight. */
  endMin: number;
  /** `endMin - startMin`, never negative (a refused span never becomes a span). */
  mins: number;
}

export interface RangeParse {
  /** Every span that resolved to a positive (or zero-length) duration. */
  spans: DowntimeSpan[];
  /** Sum of `spans[].mins`. 0 when nothing resolved. */
  totalMins: number;
  /** Lines/tokens that could not become a span, each already phrased for an operator. */
  warnings: string[];
  /** Source text of every start with no end. */
  openRanges: string[];
  /** True when the bare-time pairing rule fired (the brown-out shape). */
  pairedBareTimes: boolean;
}

export interface DurationParse {
  /** Total minutes the DURATION cell states, or null when it says nothing readable. */
  mins: number | null;
  warnings: string[];
}

/** How a downtime row's minutes were arrived at. */
export type DowntimeMinutesSource = "ranges" | "duration" | "none";

export interface DowntimeMinutes {
  totalMins: number;
  source: DowntimeMinutesSource;
  /** The DURATION cell's own figure, whenever it parsed — even when the ranges won. */
  durationMins: number | null;
  /** The ranges' figure, whenever any span resolved. */
  rangesMins: number | null;
  /** True when both sides parsed and differ by MORE than one minute. */
  disagrees: boolean;
  warnings: string[];
  parse: RangeParse;
}

/** Tolerance for "the duration cell agrees with the list", in minutes. */
export const DURATION_AGREEMENT_TOLERANCE_MINS = 1;

/**
 * A clock time with an optional meridiem. `NN` is MC's spelling of noon (`12:05 NN`).
 * Deliberately requires the colon-or-dot separator and 2-digit minutes, so an inverter
 * setting typed into the wrong column (`29:29`, `30:30`) fails the 0-23 hour check below
 * rather than being read as a time.
 */
const TIME_SRC = String.raw`(\d{1,2})[:.](\d{2})\s*(A\.?M\.?|P\.?M\.?|N\.?N\.?)?`;
/** A span (`8:00 AM-9:40 AM`) or, failing that, a single time. Ordered: span wins. */
const ITEM_RE = new RegExp(
  String.raw`${TIME_SRC}\s*[-‐-―]\s*${TIME_SRC}|${TIME_SRC}`,
  "gi",
);

/** The hour at which the plant day starts — the anchor for a meridiem-less time. */
export const PLANT_DAY_START_HOUR = 8;

/**
 * Resolve one `H:MM [meridiem]` to minutes from midnight, or null when it is not a
 * clock time at all. `hour` 0-23 and `minute` 0-59 are enforced here, which is what
 * keeps `29:29` (an inverter setting) out of the arithmetic.
 */
function toMinutes(hourRaw: string, minRaw: string, mer: string | undefined): number | null {
  const h = parseInt(hourRaw, 10);
  const m = parseInt(minRaw, 10);
  if (!Number.isFinite(h) || !Number.isFinite(m)) return null;
  if (h > 23 || m > 59) return null;

  const tag = (mer ?? "").replace(/[.\s]/g, "").toUpperCase();
  if (tag === "AM") return (h % 12) * 60 + m;
  if (tag === "PM") return ((h % 12) + 12) * 60 + m;
  // `NN` = noon. MC only ever writes it on the 12 o'clock hour; anything else with an
  // `NN` tag is treated as afternoon, the same as PM, rather than silently as morning.
  if (tag === "NN") return h === 12 ? 12 * 60 + m : ((h % 12) + 12) * 60 + m;

  // No meridiem — THE PLANT-DAY RULE. 8..12 is the morning (12 = noon); 1..7 is the
  // afternoon; 0 and 13..23 are already unambiguous 24h readings.
  if (h >= PLANT_DAY_START_HOUR && h <= 12) return h * 60 + m;
  if (h >= 1 && h <= 7) return (h + 12) * 60 + m;
  return h * 60 + m;
}

function hhmm(total: number): string {
  const h = Math.floor(total / 60);
  const m = total % 60;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}

interface RawItem {
  raw: string;
  /** Present for a dashed span. */
  start: number | null;
  end: number | null;
  /** Present for a lone time. */
  lone: number | null;
}

/**
 * Normalize a raw cell value to the text these parsers read.
 *
 * A Date can genuinely arrive here: Excel types a cell holding ONLY `8:00` as a TIME, and
 * exceljs surfaces that as a Date (UTC parts, per lib/xlsx.ts). Rendering it back to
 * `HH:MM` keeps such a cell readable instead of silently contributing nothing — the same
 * value it would have carried had the operator typed a second range beside it.
 */
export function cellText(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (value instanceof Date) {
    const h = value.getUTCHours();
    const m = value.getUTCMinutes();
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
  }
  if (typeof value === "boolean") return "";
  return String(value);
}

/** Split a cell into non-blank, trimmed lines (the extractor's own convention). */
function lines(text: string): string[] {
  return text
    .split(/\r\n|\r|\n/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
}

/**
 * Parse MC's time-ranges cell into stoppage spans.
 *
 * Tokenising is done PER LINE so an end time on one line can never be paired with a start
 * on the next — `8:00-8:10` followed by `10:20-11:25` is two spans of 10 and 65 minutes,
 * never one of 205.
 */
export function parseTimeRanges(raw: unknown): RangeParse {
  const text = cellText(raw);
  const items: RawItem[] = [];
  let sawDashedSpan = false;

  for (const line of lines(text)) {
    ITEM_RE.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = ITEM_RE.exec(line)) !== null) {
      // Groups 1-3 = span start, 4-6 = span end, 7-9 = lone time.
      if (m[1] !== undefined && m[4] !== undefined) {
        const start = toMinutes(m[1], m[2], m[3]);
        const end = toMinutes(m[4], m[5], m[6]);
        if (start === null || end === null) continue; // not a clock time (e.g. 29:29)
        sawDashedSpan = true;
        items.push({ raw: m[0].trim(), start, end, lone: null });
      } else if (m[7] !== undefined) {
        const lone = toMinutes(m[7], m[8], m[9]);
        if (lone === null) continue;
        items.push({ raw: m[0].trim(), start: null, end: null, lone });
      }
    }
  }

  const spans: DowntimeSpan[] = [];
  const warnings: string[] = [];
  const openRanges: string[] = [];

  const push = (raw: string, start: number, end: number): void => {
    if (end < start) {
      warnings.push(
        `downtime range '${raw}' ends before it starts (${hhmm(start)} → ${hhmm(end)}) — ` +
          `counted as 0 minutes`,
      );
      return;
    }
    spans.push({ raw, startMin: start, endMin: end, mins: end - start });
  };

  const bare = items.filter((i) => i.lone !== null);
  // THE BROWN-OUT SHAPE: no dashed span anywhere, but several bare times. Only then are
  // consecutive marks read as stoppages. See the module header.
  const pairedBareTimes = !sawDashedSpan && bare.length >= 2;

  if (pairedBareTimes) {
    // Consecutive marks (1&2, 3&4, …) are the stoppages.
    for (let i = 0; i + 1 < bare.length; i += 2) {
      const a = bare[i];
      const b = bare[i + 1];
      push(`${a.raw}-${b.raw}`, a.lone as number, b.lone as number);
    }
    if (bare.length % 2 === 1) {
      const last = bare[bare.length - 1];
      openRanges.push(last.raw);
      warnings.push(
        `downtime time '${last.raw}' has no matching end time — counted as 0 minutes`,
      );
    }
  } else {
    for (const item of items) {
      if (item.lone !== null) {
        openRanges.push(item.raw);
        warnings.push(
          `downtime time '${item.raw}' has no end time (open range) — counted as 0 minutes`,
        );
        continue;
      }
      push(item.raw, item.start as number, item.end as number);
    }
  }

  const totalMins = spans.reduce((s, x) => s + x.mins, 0);
  return { spans, totalMins, warnings, openRanges, pairedBareTimes };
}

/**
 * Parse MC's hand-written DURATION cell. Multi-line: each line is its own figure and the
 * lines SUM (`"12 MINUTES\n40 MINUTES"` = 52).
 *
 * The unit words are read, not stripped. The old parse removed every non-digit, which
 * turned `"1 HOUR & 40 MINUTES"` into the number 140 — a value that is neither the hours
 * nor the minutes nor their total. When a line names no unit at all it falls back to that
 * legacy digit-strip and is read as a bare minute count.
 */
export function parseDurationText(raw: unknown): DurationParse {
  const text = cellText(raw);
  const warnings: string[] = [];
  let total = 0;
  let any = false;

  for (const line of lines(text)) {
    const upper = line.toUpperCase();
    const unitRe = /(\d+(?:\.\d+)?)\s*(HOURS?|HRS?|MINUTES?|MINS?|SECONDS?|SECS?)\b/g;
    let m: RegExpExecArray | null;
    let lineMins = 0;
    let lineAny = false;
    while ((m = unitRe.exec(upper)) !== null) {
      const n = parseFloat(m[1]);
      if (!Number.isFinite(n)) continue;
      const unit = m[2];
      lineAny = true;
      if (unit.startsWith("H")) lineMins += n * 60;
      else if (unit.startsWith("S")) lineMins += n / 60;
      else lineMins += n;
    }
    if (lineAny) {
      total += lineMins;
      any = true;
      continue;
    }
    // No unit word — the legacy digit-strip, read as bare minutes.
    const digits = upper.replace(/[^0-9.]/g, "");
    const f = digits === "" ? NaN : Number(digits);
    if (Number.isFinite(f)) {
      total += f;
      any = true;
    } else {
      warnings.push(`could not parse downtime minutes from '${line}'`);
    }
  }

  return { mins: any ? total : null, warnings };
}

/**
 * THE resolution: minutes come from the ranges, with the DURATION cell as a cross-check.
 *
 * Precedence, and the reason for each rung:
 *   1. Any span resolved → the RANGES win. If DURATION also parsed and differs by more
 *      than a minute, `disagrees` is set and a warning names BOTH figures. The ranges are
 *      trusted because the duration cell has been measured to summarise only the first
 *      span; nothing is silently corrected in either direction.
 *   2. No span, but DURATION parsed → use DURATION (the pre-L-051 behaviour), with a
 *      warning saying the list could not be read. This is what keeps a legacy sheet, and
 *      the ge60 edge fixture's DURATION-only shape, working.
 *   3. Neither → 0 minutes. The caller's own emission gate decides whether a row exists
 *      at all (a reason with no minutes is still a row).
 */
export function resolveDowntimeMinutes(
  rangesText: unknown,
  durationText: unknown,
): DowntimeMinutes {
  const parse = parseTimeRanges(rangesText);
  const dur = parseDurationText(durationText);
  const warnings = [...parse.warnings];

  const rangesMins = parse.spans.length > 0 ? parse.totalMins : null;
  const durationMins = dur.mins;

  if (rangesMins !== null) {
    const disagrees =
      durationMins !== null &&
      Math.abs(durationMins - rangesMins) > DURATION_AGREEMENT_TOLERANCE_MINS;
    if (disagrees) {
      warnings.push(
        `downtime DURATION cell says ${round1(durationMins as number)} min but the time ` +
          `ranges add up to ${round1(rangesMins)} min — used the ranges`,
      );
    }
    return {
      totalMins: rangesMins,
      source: "ranges",
      durationMins,
      rangesMins,
      disagrees,
      warnings,
      parse,
    };
  }

  if (durationMins !== null) {
    warnings.push(...dur.warnings);
    warnings.push(
      "no downtime time range could be read — fell back to the DURATION cell",
    );
    return {
      totalMins: durationMins,
      source: "duration",
      durationMins,
      rangesMins: null,
      disagrees: false,
      warnings,
      parse,
    };
  }

  warnings.push(...dur.warnings);
  return {
    totalMins: 0,
    source: "none",
    durationMins: null,
    rangesMins: null,
    disagrees: false,
    warnings,
    parse,
  };
}

/** Trim float noise for an operator-facing sentence (56.999999 → 57). */
function round1(x: number): number {
  return Math.round(x * 10) / 10;
}
